name: Build

on:
  [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'yarn'
    - name: Install deps
      run: yarn
    - name: Build windows nsis installer
      run: npm run nsis
    - name: Build windows nsis installer (x86/ia32)
      run: npm run nsis-ia32
    - name: Build windows 7zip protable version
      run: npm run 7zip
    - name: Build windows 7zip protable version (x86/ia32)
      run: npm run 7zip-ia32
    - uses: actions/upload-artifact@v2
      with:
        path: |
          packaged/wnr-*-Setup-64.exe
          packaged/wnr-*-Setup-32.exe
          packaged/wnr-*-Win-64.7z
          packaged/wnr-*-Win-32.7z

  build-macos:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'yarn'
    - name: Install deps
      run: yarn
    - name: Build macos version
      run: npm run mac
    - uses: actions/upload-artifact@v2
      with:
        path: packaged/wnr-*-MacOS.dmg

  build-linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'yarn'
    - name: Install deps
      run: yarn
    - name: Build AppImage
      run: npm run appimage
    - uses: actions/upload-artifact@v2
      with:
        path: packaged/wnr-*-Linux.AppImage
